apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-api
  labels:
    app: netflix-api-tag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-api-tag
  template:
    metadata:
      labels:
        app: netflix-api-tag
    spec:
      containers:
      - name: netflix-api-tag
        image: diskoproject/netflix:v1.0.1
       
---

apiVersion: v1
kind: Service
metadata:
  name: netflix-api-service
spec:
  selector:
    app: netflix-api-tag
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
